# Generated by Django 3.1.2 on 2020-10-12 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='brief',
            field=ckeditor.fields.RichTextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
