# Generated by Django 3.1.2 on 2020-10-12 10:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_story_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='brief',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
