# Generated by Django 3.1.2 on 2020-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20201012_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='coverImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
