# Generated by Django 3.1.2 on 2020-10-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20201016_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
