# Generated by Django 3.1.2 on 2020-10-26 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_drawing_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
