# Generated by Django 3.1.2 on 2020-10-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
