# Generated by Django 3.1.2 on 2020-10-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20201013_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='image_cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
