# Generated by Django 3.1.2 on 2020-10-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20201013_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
