# Generated by Django 3.1.2 on 2020-10-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_writing_ispublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.writing')),
            ],
        ),
    ]
