# Generated by Django 3.1.2 on 2020-10-13 08:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
