# Generated by Django 3.1.2 on 2020-10-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20201013_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
