# Generated by Django 3.1.2 on 2020-10-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_comic_ispublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comic')),
            ],
        ),
    ]
